language: go
go:
  - "1.13"
  - "1.14"
  - master

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./pkg/...

after_success:
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux
  - osx
