name: Build

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.16"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make
        run: make build-all
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v1
        with:
          name: darwin
          path: dist/darwin
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: dist/linux
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: dist/windows
